export const AUTH_START = 'AUTH_START'
export const AUTH_INIT = 'AUTH_INIT'
export const AUTH_LOADED = 'AUTH_LOADED'

export const SUBJECTS_LOADED = 'SUBJECTS_LOADED'
export const SUBJECT_LOADED = 'SUBJECT_LOADED'
export const SUBJECT_NAME_LOAD_INIT = 'SUBJECT_NAME_LOAD_INIT'
export const SUBJECT_NAME_LOADED = 'SUBJECT_NAME_LOADED'
export const SUBJECT_INIT = 'SUBJECT_INIT'