export const AUTH_START = 'AUTH_START';
export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_LOADED = 'AUTH_LOADED';
export const AUTH_FAILED = 'AUTH_FAILED';

export const FETCH_SUBJECT = 'FETCH_SUBJECT';
export const FETCH_SUBJECT_SUCCESS = 'FETCH_SUBJECT_SUCCESS';
export const LOAD_SUBJECTS = 'LOAD_SUBJECTS';
export const LOAD_SUBJECTS_SUCCESS = 'LOAD_SUBJECTS_SUCCESS';
export const LOAD_SUBJECTS_FAILURE = 'LOAD_SUBJECTS_FAILURE';
export const SAVE_SUBJECT = 'SAVE_SUBJECT';
export const SAVE_SUBJECT_SUCCESS = 'SAVE_SUBJECT_SUCCESS';
export const SAVE_SUBJECT_FAILURE = 'SAVE_SUBJECT_FAILURE';

export const FETCH_REPOS = 'FETCH_REPOS';
export const FETCH_REPOS_SUCCESS = 'FETCH_REPOS_SUCCESS';
export const FETCH_REPOS_FAILURE = 'FETCH_REPOS_FAILURE';

export const FETCH_ASSIGNMENTS = 'FETCH_ASSIGNMENTS';
export const FETCH_ASSIGNMENTS_SUCCESS = 'FETCH_ASSIGNMENTS_SUCCESS';
export const FETCH_ASSIGNMENT = 'FETCH_ASSIGNMENT';
export const FETCH_ASSIGNMENT_SUCCESS = 'FETCH_ASSIGNMENT_SUCCESS';
export const SAVE_ASSIGNMENT = 'SAVE_ASSIGNMENT';
export const SAVE_ASSIGNMENT_SUCCESS = 'SAVE_ASSIGNMENT_SUCCESS';
export const SAVE_ASSIGNMENT_FAILURE = 'SAVE_ASSIGNMENT_FAILURE';

export const FETCH_WORK = 'FETCH_WORK';
export const FETCH_WORK_SUCCESS = 'FETCH_WORK_SUCCESS';
export const FETCH_WORKS = 'FETCH_WORKS';
export const FETCH_WORKS_SUCCESS = 'FETCH_WORKS_SUCCESS';

export const GRADE_WORK = 'GRADE_WORK';
export const GRADE_WORK_SUCCESS = 'GRADE_WORK_SUCCESS';

export const LOAD_GITHUB_ORGS_SUCCESS = 'LOAD_GITHUB_ORGS_SUCCESS';

export const LOAD_GITHUB_REPOS_SUCCESS = 'LOAD_GITHUB_REPOS_SUCCESS';

export const SUBJECTS_RECEIVED = 'SUBJECTS_RECIEVED';
export const SUBJECTS_LOADED = 'SUBJECTS_LOADED';
export const SUBJECT_LOADED = 'SUBJECT_LOADED';
export const SUBJECT_NAME_LOAD_INIT = 'SUBJECT_NAME_LOAD_INIT';
export const SUBJECT_NAME_LOADED = 'SUBJECT_NAME_LOADED';
export const SUBJECT_INIT = 'SUBJECT_INIT';

export const ASSIGNMENT_LOADED = 'ASSIGNMENT_LOADED';
export const ASSIGNMENTS_LOADED= 'ASSIGNMENTS_LOADED';

export const HOMEWORK_LOADED = 'HOMEWORK_LOADED';
export const LOADING_HOMEWORK = 'LOADING_HOMEWORK';
